import type { Currency } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'EUR', name: 'Euro' },
  { code: 'USD', name: 'Dollar américain' },
  { code: 'GBP', name: 'Livre sterling' },
  { code: 'JPY', name: 'Yen japonais' },
  { code: 'MAD', name: 'Dirham marocain' },
  { code: 'CHF', name: 'Franc suisse' },
  { code: 'CAD', name: 'Dollar canadien' },
  { code: 'AUD', name: 'Dollar australien' },
  { code: 'CNY', name: 'Yuan chinois' },
  { code: 'SEK', name: 'Couronne suédoise' },
  { code: 'NOK', name: 'Couronne norvégienne' },
  { code: 'DKK', name: 'Couronne danoise' },
  { code: 'NZD', name: 'Dollar néo-zélandais' },
  { code: 'SGD', name: 'Dollar de Singapour' },
  { code: 'HKD', name: 'Dollar de Hong Kong' },
  { code: 'KRW', name: 'Won sud-coréen' },
  { code: 'INR', name: 'Roupie indienne' },
  { code: 'BRL', name: 'Réal brésilien' },
  { code: 'MXN', name: 'Peso mexicain' },
  { code: 'ZAR', name: 'Rand sud-africain' },
  { code: 'TRY', name: 'Livre turque' },
  { code: 'RUB', name: 'Rouble russe' },
  { code: 'PLN', name: 'Zloty polonais' },
  { code: 'CZK', name: 'Couronne tchèque' },
  { code: 'HUF', name: 'Forint hongrois' },
  { code: 'RON', name: 'Leu roumain' },
  { code: 'BGN', name: 'Lev bulgare' },
  { code: 'HRK', name: 'Kuna croate' },
  { code: 'ISK', name: 'Couronne islandaise' },
  { code: 'AED', name: 'Dirham des Émirats' },
  { code: 'SAR', name: 'Riyal saoudien' },
  { code: 'THB', name: 'Baht thaïlandais' },
  { code: 'IDR', name: 'Roupie indonésienne' },
  { code: 'MYR', name: 'Ringgit malaisien' },
  { code: 'PHP', name: 'Peso philippin' },
];
